
behavior_tree_node:
  ros__parameters:
    use_sim_time: True
    goal_list: 
    - WS1
    - HOME
    WS1:
        position: -3.0,-1.0
        orientation: 3.7
    WS2:
        position: 0.64,1.83
        orientation: 1.0

    WS3:
        position: -3.0,0.0
        orientation: 1.0
    HOME: 
        position: -5.327,-2.481
        orientation: 0.461
    plugin_lib_names:
    - move_gripper_action_bt_node
    - move_manipulator_action_bt_node
    - plan_manipulator_path_action_bt_node
    - object_search_action_bt_node
    - empty_frame_condition_bt_node
    - navigate_vehicle_bt_node

